export const GET_FIRST_START = 'GET_FIRST_START';
export const GET_FIRST_SUCCESS = 'GET_FIRST_SUCCESS';
export const GET_FIRST_FAIL = 'GET_FIRST_FAIL';
export const POST_FIRST_START = 'POST_FIRST_START';
export const POST_FIRST_SUCCESS = 'POST_FIRST_SUCCESS';
export const POST_FIRST_FAIL = 'POST_FIRST_FAIL';

export const GET_SECOND_START = 'GET_SECOND_START';
export const GET_SECOND_SUCCESS = 'GET_SECOND_SUCCESS';
export const GET_SECOND_FAIL = 'GET_SECOND_FAIL';
export const POST_SECOND_START = 'POST_SECOND_START';
export const POST_SECOND_SUCCESS = 'POST_SECOND_SUCCESS';
export const POST_SECOND_FAIL = 'POST_SECOND_FAIL';

export const GET_THIRD_START = 'GET_THIRD_START';
export const GET_THIRD_SUCCESS = 'GET_THIRD_SUCCESS';
export const GET_THIRD_FAIL = 'GET_THIRD_FAIL';
export const POST_THIRD_START = 'POST_THIRD_START';
export const POST_THIRD_SUCCESS = 'POST_THIRD_SUCCESS';
export const POST_THIRD_FAIL = 'POST_THIRD_FAIL';

export const GET_FOURTH_START = 'GET_FOURTH_START';
export const GET_FOURTH_SUCCESS = 'GET_FOURTH_SUCCESS';
export const GET_FOURTH_FAIL = 'GET_FOURTH_FAIL';